from weasyprint import HTML
from jinja2 import Template
import base64
from app.logging_config import logger

class PDFGenerator:
    """Generate PDF reports from markdown content"""
    
    async def generate_pdf(self, report_data: dict) -> str:
        """Generate PDF from report data"""
        try:
            # Create HTML template
            html_content = self._create_html_template(report_data)
            
            # Generate PDF
            pdf_bytes = HTML(string=html_content).write_pdf()
            
            # Convert to base64 for API response
            pdf_base64 = base64.b64encode(pdf_bytes).decode('utf-8')
            
            return pdf_base64
            
        except Exception as e:
            logger.error("PDF generation failed", error=str(e))
            raise e
    
    def _create_html_template(self, report_data: dict) -> str:
        """Create HTML template for PDF generation"""
        
        template_str = """
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>{{ title }}</title>
            <style>
                body { font-family: Arial, sans-serif; line-height: 1.6; margin: 40px; }
                h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
                h2 { color: #34495e; margin-top: 30px; }
                h3 { color: #7f8c8d; }
                .content { margin: 20px 0; }
                .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #bdc3c7; 
                         font-size: 12px; color: #7f8c8d; }
            </style>
        </head>
        <body>
            <h1>{{ title }}</h1>
            <div class="content">
                {{ content|safe }}
            </div>
            <div class="footer">
                Generated by AI Research System | Confidence: {{ confidence }}%
            </div>
        </body>
        </html>
        """
        
        template = Template(template_str)
        return template.render(
            title=report_data.get('title', 'Research Report'),
            content=report_data.get('report_content', '').replace('\n', '<br>'),
            confidence=int((report_data.get('fact_check_confidence', 0) or 0) * 100)
        )

pdf_generator = PDFGenerator()
